Rails.application.routes.draw do
  get 'dashboard' => 'dashboard#index'
  get 'contact' => 'contacts#new', :as => 'contact'
  get 'contacts/create'
  get 'partners/new'
  get 'partners/create'
  get 'partners/edit'
  get 'partners/update'
  get 'partners/index'
  get 'partners/show'
  get 'partners/destroy'
  get 'researchs/new'
  get 'researchs/create'
  get 'researchs/edit'
  get 'researchs/update'
  get 'researchs/index'
  get 'researchs/show'
  get 'researchs/destroy'
  get 'cnewses/new'
  get 'cnewses/create'
  get 'cnewses/edit'
  get 'cnewses/update'
  get 'cnewses/index'
  get 'cnewses/show'
  get 'cnewses/destroy'
  get 'cribraries/new'
  get 'cribraries/create'
  get 'cribraries/edit'
  get 'cribraries/update'
  get 'cribraries/index'
  get 'cribraries/show'
  get 'cribraries/destroy'
  get 'assessmentblogs/new'
  get 'assessmentblogs/create'
  get 'assessmentblogs/edit'
  get 'assessmentblogs/update'
  get 'assessmentblogs/index'
  get 'assessmentblogs/show'
  get 'assessmentblogs/destroy'
  get 'assessments/new'
  get 'assessments/create'
  get 'assessments/edit'
  get 'assessments/update'
  get 'assessments/index'
  get 'assessments/show'
  get 'assessments/destroy'
  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  get 'entrepreneurblogs/new'
  get 'entrepreneurblogs/create'
  get 'entrepreneurblogs/edit'
  get 'entrepreneurblogs/update'
  get 'entrepreneurblogs/index'
  get 'entrepreneurblogs/show'
  get 'entrepreneurblogs/destroy'
  get 'entrepreneurs/new'
  get 'entrepreneurs/create'
  get 'entrepreneurs/edit'
  get 'entrepreneurs/update'
  get 'entrepreneurs/index'
  get 'entrepreneurs/show'
  get 'entrepreneurs/destroy'
  get 'about/index'


  resources :entrepreneurblogs, :clibraries, :assessmentblogs, :cnewses, :entrepreneurs, :researchs, :assessments, :partners
  resources :contacts, only: [:new, :create, :destory]

  root 'about#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
